import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { LoadingPage } from "~/components/loading";
import TaskTable from "~/components/task-table";
import { Button } from "~/components/ui/button";
import { cn, todoToTask } from "~/lib/utils";

import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const { user, isLoaded: isUserLoaded, isSignedIn } = useUser();

  // const {
  //   fetchNextPage,
  //   fetchPreviousPage,
  //   hasNextPage,
  //   hasPreviousPage,
  //   isFetchingNextPage,
  //   isFetchingPreviousPage,
  //   isLoading,
  //   isError,
  //   data,
  // } = api.tasks.getTasksForUser.useInfiniteQuery({});
  // const dd = data?.pages[0];

  const { data, isLoading, isError } = api.tasks.getTasksForUser.useQuery({});
  // const { todos, cursor } = data;

  const renderLoggedOutView = () => {
    return (
      <>
        <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
          TODO <span className="text-[hsl(280,100%,70%)]">Next</span>
        </h1>
        <p className="text-center text-white">
          A todo and task tracking app built in T3 stack
          <br />
          Sign up using your google or github account today
        </p>
        <div className="">
          <Button asChild className="bg-[hsl(280,100%,70%)] text-white">
            <SignInButton />
          </Button>
        </div>
      </>
    );
  };

  const renderUserView = () => {
    return isSignedIn ? (
      <div className="w-full">
        <TaskTable
          tasks={todoToTask(data?.todos)}
          userName={user.username ?? ""}
          userImage={user.imageUrl ?? ""}
          onNewClick={() => console.log("Add New")}
          isLoading={isLoading}
        />
      </div>
    ) : (
      renderLoggedOutView()
    );
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={cn(
          "flex min-h-screen flex-col items-center gap-12 bg-gradient-to-b from-[#2e026d] to-[#15162c]",
          isSignedIn ? "items-start" : "",
        )}
      >
        {isUserLoaded ? renderUserView() : <LoadingPage />}
      </main>
    </>
  );
}
